version: '3.9'
services:
  frontend:
    container_name: 'app_frontend'
    build: ./frontend
    ports:
      - 3000:3000
    working_dir: /app-frontend
    depends_on:
      backend:
        condition: service_healthy
    # Os `healthcheck` devem garantir que a aplicação
    # está operacional, antes de liberar o container
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]
      timeout: 10s
      retries: 5
  backend:
    container_name: app_backend
    build: ./backend
    ports:
      - 3001:3001
    working_dir: /app-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PORT=3001
      - SECRET=secret
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_HOST=db
      - DB_PORT=5432
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 5
  db:
    image: postgres:latest
    container_name: db
    ports:
      - 3002:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: 'always'
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "db_prod"]
      retries: 5
    cap_add:
      - SYS_NICE # Deve omitir alertas menores que nao irao impactar